[package]
name = "adventofcode"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.11.0"

[[bin]]
name = "day01"
path = "day01/day01.rs"

[[bin]]
name = "day02"
path = "day02/day02.rs"

[[bin]]
name = "day03"
path = "day03/day03.rs"
